### ISSUE TITLE
Can't register service

### ISSUE THREAD

**Issue by clemorphy** [lucatume/klein52#1]
Hello.

I am trying to register Twig as a service with this simple code:
```
<?php

require_once __DIR__ . '/vendor/autoload.php';

klein_load();

respond(function ($request, $response, $app) {

    $app->register('twig', function() {
        $loader = new Twig_Loader_Filesystem('views');
        return new Twig_Environment($loader);
    });
});

respond('GET', '/', function ($request, $response, $app) {
    $results = "stuff";
    echo $app->twig->render('test.html.twig', array('data' => $results));
});

dispatch();
```
All I get is a notice when I register the service (`$app->register`) :
`Notice: Undefined index: twig in /Applications/MAMP/htdocs/IDEAFACTORY/www/vendor/lucatume/klein52/klein.php on line 1053`

And a fatal error when I try to call the registered service (`echo $app->twig->render`) :
```
Fatal error: Uncaught exception 'ErrorException' with message 'exception 'InvalidArgumentException' with message 'Unknown service twig' in /Applications/MAMP/htdocs/IDEAFACTORY/www/vendor/lucatume/klein52/klein.php:1032 Stack trace: #0 /Applications/MAMP/htdocs/IDEAFACTORY/www/index.php(17): _App->__get('twig') #1 [internal function]: {closure}(Object(_Request), Object(_Response), Object(_App), 0, Array) #2 /Applications/MAMP/htdocs/IDEAFACTORY/www/vendor/lucatume/klein52/klein.php(242): call_user_func(Object(Closure), Object(_Request), Object(_Response), Object(_App), 0, Array) #3 /Applications/MAMP/htdocs/IDEAFACTORY/www/index.php(20): dispatch() #4 {main}' in /Applications/MAMP/htdocs/IDEAFACTORY/www/vendor/lucatume/klein52/klein.php:733 Stack trace: #0 /Applications/MAMP/htdocs/IDEAFACTORY/www/vendor/lucatume/klein52/klein.php(244): _Response->error(Object(InvalidArgumentException)) #1 /Applications/MAMP/htdocs/IDEAFACTORY/www/index.php(20): dispatch() #2 {main} thrown in /Applications/MAMP/htdocs/IDEAFACTORY/www/vendor/lucatume/klein52/klein.php on line 733
```

Any idea ?

**Comment by lucatume** [comment]
Hi there,

not really many ideas as I've not touched that part of the original code completely.
Did you run an XDebug session? If so: do you have any more information?

**Comment by clemorphy** [comment]
Here is what xDebug says:
![screencapture-ideafactory-dev-test-1511734072465](https://user-images.githubusercontent.com/1913472/33244863-2656d4fc-d2ff-11e7-9480-203330e29f5a.png)

**Comment by lucatume** [comment]
Hi there,

could you try the latest version of the `master` branch I've just pushed and let me know if it solves the issue?

To try it out: `composer require lucatume/klein52:dev-master`.

**Comment by clemorphy** [comment]
I tried with the latest version, it seems to work well now.
Thank you 😃

**Comment by lucatume** [comment]
Perfect, thanks for your feedback.
