### ISSUE TITLE
Error with $request->validate()

### ISSUE THREAD

**Issue by clemorphy** [lucatume/klein52#2]
Hi

When I try to use the `$request->validate() method`, I have the following error :
`Notice: Use of undefined constant self - assumed 'self' in /Applications/MAMP/htdocs/IDEAFACTORY/www/vendor/lucatume/klein52/klein.php on line 875`

For lines 875 to 886

**Comment by lucatume** [comment]
Argh.

Thanks for reporting it. The fix should be in the `master` branch; try it out using `composer require lucatume/klein52:dev-master`.

If it does not work please let me know the PHP version you are using, thanks!

**Comment by clemorphy** [comment]
`$request->validate()` is working fine now, thanx.
It throws an exception when the validation fails, but I guess this is the expected behaviour.

**Comment by lucatume** [comment]
Thanks for reporting back.

Yes, the Exception is expected.
