### ISSUE TITLE
Examples not compatible with PHP 5.2

### ISSUE THREAD

**Issue by clemorphy** [lucatume/klein52#3]
Hi

The examples given are not compatible with PHP 5.2 because they use anonymous functions :
```
<?php
respond(function () {
    echo 'Hello World!';
});
```
Tested with PHP 5.2.17, it gives the error :

> PHP Parse error:  syntax error, unexpected T_FUNCTION, expecting ')' in xxxxxxxxxxxxxxxxxx.php on line 11

Anonymous functions are available from PHP 5.3+

**Comment by lucatume** [comment]
I've not used PHP 5.2 compatible examples for brevity but guess I could add one or two and a disclaimer; thanks for reporting this.

**Comment by lucatume** [comment]
I've updated the readme, closing.
